- name: Enable SELinux
  ansible.posix.selinux:
    state: enforcing
    policy: targeted
  tags:
    - ansibullbot
    - ansibullbot_selinux
    - notest

- name: Set fcontext
  community.general.sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
  notify: restorecon
  loop:
    - target: "{{ ansibullbot_home_dir }}(/.*)?"
      setype: initrc_var_run_t

    - target: '{{ ansibullbot_clone_path }}/scripts/.*\.cgi'
      setype: httpd_sys_script_exec_t
  tags:
    - ansibullbot
    - ansibullbot_selinux
    - notest

- name: Copy type enforcement file
  copy:
    src: ansibot_status.te
    dest: "{{ ansibullbot_home_dir }}"
    owner: "{{ ansibullbot_user }}"
    group: "{{ ansibullbot_group }}"
    mode: '0644'
  notify: update_selinux_module
  tags:
    - ansibullbot
    - ansibullbot_selinux
    - notest

- name: Set SELinux booleans needed for the ansible_actions.py script
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_can_network_connect
    - httpd_unified
    - httpd_enable_cgi

- meta: flush_handlers
  tags:
    - ansibullbot
    - ansibullbot_selinux
    - notest
