Vagrant.configure(2) do |config|

  # config.dns.tld = "vagrant.dev"

  # CentOS 7
  config.vm.define "ansibullbot-centos7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "ansibullbot-centos7"
    centos7.vm.network "private_network", ip: "10.77.19.111"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "ansibullbot-centos7"
      vbox.cpus = 1
      vbox.memory = 512
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
